from nltk.corpus import wordnet as wn

mappings_by_hand = {
    'Touring': {
        'title': wn.synset('tour.v.01'),
        'FEs': {
            'Attraction': wn.synset('attraction.n.02'),
            'Tourist': wn.synset('tourist.n.01'),
            'Co-participant': wn.synset('participant.n.01'),
            'Depictive': wn.synset('delineative.s.01'),
            'Duration': wn.synset('duration.n.01'),
            'Ground': wn.synset('background.n.02'),
            'Manner': wn.synset('manner.n.01'),
            'Means': wn.synset('means.n.01'),
            'Particular_iteration': wn.synset('iteration.n.03'),
            'Place': wn.synset('topographic_point.n.01'),
            'Purpose': wn.synset('purpose.n.01'),
            'Time': wn.synset('time.n.01')
        },
        'LUs': {
            'do.v': wn.synset('do.v.13'),
            'see.v': wn.synset('visit.v.01'),
            'sight seer.n': wn.synset('sightseer.n.01'),
            'sight-see.v': wn.synset('sightsee.v.01'),
            'sights.n': wn.synset('sight.n.02'),
            'tour.n': wn.synset('tour.n.01'),
            'tour.v': wn.synset('tour.v.01'),
            'tourism.n': wn.synset('tourism.n.01'),
            'tourist.n': wn.synset('tourist.n.01')
        }
    },
    'Cause_fluidic_motion': {
        'title': wn.synset('causal_agent.n.01'),
        'FEs': {
            'Agent': wn.synset('agentive_role.n.01'),
            'Area': wn.synset('area.n.01'),
            'Cause': wn.synset('cause.n.01'),
            'Fluid': wn.synset('fluid.n.02'),
            'Goal': wn.synset('finish.n.04'),
            'Path': wn.synset('path.n.04'),
            'Source': wn.synset('beginning.n.04'),
            'Distance': wn.synset('distance.n.01'),
            'Explanation': wn.synset('explanation.n.01'),
            'Instrument': wn.synset('instrumental_role.n.01'),
            'Manner': wn.synset('manner.n.01'),
            'Means': wn.synset('means.n.02'),
            'Place': wn.synset('topographic_point.n.01'),
            'Purpose': wn.synset('purpose.n.01'),
            'Result': wn.synset('consequence.n.01'),
            'Time': wn.synset('time.n.01')
        },
        'LUs': {
            'dribble.v': wn.synset('trickle.v.01'),
            'drip.v': wn.synset('drip.v.01'),
            'pump.v': wn.synset('pump.v.05'),
            'spatter.v': wn.synset('spatter.v.01'),
            'spew.v': wn.synset('spew.v.02'),
            'spill.v': wn.synset('spill.v.01'),
            'splash.v': wn.synset('sprinkle.v.02'),
            'splatter.v': wn.synset('spill.v.01'),
            'spray.v': wn.synset('spray.v.02'),
            'sprinkle.v': wn.synset('sprinkle.v.02'),
            'squirt.v': wn.synset('squirt.v.01')
        }
    },
    'Submitting_documents': {
        'title': wn.synset('submit.v.01'),
        'FEs': {
            'Authority': wn.synset('authority.n.02'),
            'Documents': wn.synset('document.n.01'),
            'Submittor': None,
            'Beneficiary': wn.synset('benefactive_role.n.01'),
            'Depictive': wn.synset('delineative.s.01'),
            'Explanation': wn.synset('explanation.n.01'),
            'Imposed_purpose': wn.synset('purpose.n.01'),
            'Manner': wn.synset('manner.n.01'),
            'Means': wn.synset('means.n.02'),
            'Place': wn.synset('topographic_point.n.01'),
            'Purpose': wn.synset('purpose.n.01'),
            'Time': wn.synset('time.n.01')
        },
        'LUs': {
            'file.v': wn.synset('file.v.01'),
            'hand in.v': None,
            'submission.n': wn.synset('submission.n.01'),
            'submit.v': wn.synset('submit.v.01'),
            'turn in.v': wn.synset('hand_over.v.01')
        }
    },
    'Appellations': {
        'title': wn.synset('appellation.n.01'),
        'FEs': {
            'Name': wn.synset('name.n.01'),
            'Title': wn.synset('title.n.06'),
            'Context': wn.synset('context.n.01'),
            'Type': wn.synset('type.n.01')
        },
        'LUs': {
            'officer.n': wn.synset('military_officer.n.01'),
            'general.n': wn.synset('general.n.01'),
            'captain.n': wn.synset('captain.n.01'),
            'president.n': wn.synset('president.n.01'),
            'bishop.n': wn.synset('bishop.n.01'),
            'chairman.n': wn.synset('president.n.04'),
            'chairperson.n': wn.synset('president.n.04'),
            'chief.n': wn.synset('head.n.04'),
            'commander.n': wn.synset('commanding_officer.n.01'),
            'commissioner.n': wn.synset('commissioner.n.01'),
            'congressman.n': wn.synset('congressman.n.01'),
            'congresswoman.n': wn.synset('congressman.n.01'),
            'director.n': wn.synset('director.n.01'),
            'duchess.n': wn.synset('duchess.n.01'),
            'emperor.n': wn.synset('emperor.n.01'),
            'empress.n': wn.synset('empress.n.01'),
            'executive.n': wn.synset('administrator.n.03'),
            'governor.n': wn.synset('governor.n.01'),
            'headmaster.n': wn.synset('headmaster.n.01'),
            'imam.n': wn.synset('imam.n.01'),
            'kaiser.n': wn.synset('kaiser.n.01'),
            'king.n': wn.synset('king.n.01'),
            'leader.n': wn.synset('leader.n.01'),
            'legislator.n': wn.synset('legislator.n.01'),
            'maharaja.n': wn.synset('maharaja.n.01'),
            'mayor.n': wn.synset('mayor.n.01'),
            'minister.n': wn.synset('minister.n.02'),
            'mogul.n': wn.synset('baron.n.03'),
            'monarch.n': wn.synset('sovereign.n.01'),
            'official.n': wn.synset('official.n.01'),
            'premier.n': wn.synset('prime_minister.n.01'),
            'prince.n': wn.synset('prince.n.01'),
            'principal.n': wn.synset('principal.n.02'),
            'queen.n': wn.synset('queen.n.02'),
            'representative.n': wn.synset('spokesperson.n.01'),
            'secretary.n': wn.synset('secretary.n.01'),
            'shah.n': wn.synset('shah.n.01'),
            'sheik.n': wn.synset('sheik.n.01'),
            'sultan.n': wn.synset('sultan.n.01'),
            'superintendent.n': wn.synset('overseer.n.01'),
            'supervisor.n': wn.synset('supervisor.n.01'),
            'tsar.n': wn.synset('czar.n.01'),
            'mother.n': wn.synset('mother.n.01'),
            'father.n': wn.synset('father.n.01'),
            'doctor.n': wn.synset('doctor.n.01'),
            'dr.n': None,
            'mr.n': wn.synset('mister.n.01'),
            'mrs.n': wn.synset('mrs.n.01'),
            'ms.n': wn.synset('ms.n.05'),
            'miss.n': wn.synset('miss.n.03'),
            'child.n': wn.synset('child.n.02'),
            'aunt.n': wn.synset('aunt.n.01'),
            'uncle.n': wn.synset('uncle.n.01'),
            'sister.n': wn.synset('sister.n.01'),
            'brother.n': wn.synset('brother.n.01'),
            'cousin.n': wn.synset('cousin.n.01')
        }
    },
    'Evidence': {
        'title': wn.synset('evidence.n.01'),
        'FEs': {
            'Proposition': wn.synset('proposition.n.01'),
            'Support': wn.synset('confirm.v.01'),
            'Cognizer': None,
            'Degree': wn.synset('degree.n.01'),
            'Depictive': wn.synset('delineative.s.01'),
            'Domain_of_relevance': wn.synset('sphere.n.01'),
            'Manner': wn.synset('manner.n.01'),
            'Means': wn.synset('means.n.02'),
            'Result': wn.synset('consequence.n.01')
        },
        'LUs': {
            'argue.v': wn.synset('argue.v.03'),
            'argument.n': wn.synset('argument.n.01'),
            'assure.v': wn.synset('guarantee.v.02'),
            'attest.v': wn.synset('attest.v.01'),
            'confirm.v': wn.synset('confirm.v.01'),
            'contradict.v': wn.synset('contradict.v.02'),
            'corroborate.v': wn.synset('validate.v.03'),
            'credence [lend].n': None,
            'demonstrate.v': wn.synset('attest.v.01'),
            'demonstration.n': wn.synset('demonstration.n.04'),
            'disprove.v': wn.synset('disprove.v.01'),
            'evidence.n': wn.synset('evidence.n.01'),
            'evidence.v': wn.synset('attest.v.01'),
            'evince.v': wn.synset('express.v.01'),
            'from.prep': None,
            'illustrate.v': wn.synset('exemplify.v.02'),
            'imply.v': wn.synset('imply.v.01'),
            'indicate.v': wn.synset('argue.v.03'),
            'mean.v': wn.synset('mean.v.01'),
            'point (to).v': wn.synset('indicate.v.02'),
            'proof.n': wn.synset('proof.n.01'),
            'prove.v': wn.synset('testify.v.02'),
            'reflect.v': wn.synset('reflect.v.06'),
            'reveal.v': wn.synset('unwrap.v.02'),
            'rule out.v': wn.synset('preclude.v.02'),
            'show.v': wn.synset('testify.v.02'),
            'substantiate.v': wn.synset('confirm.v.01'),
            'suggest.v': wn.synset('suggest.v.03'),
            'support.v': wn.synset('confirm.v.01'),
            'tell.v': wn.synset('tell.v.07'),
            'testify.v': wn.synset('testify.v.02'),
            'verify.v': wn.synset('testify.v.02')
        }
    },
    'Strictness': {
        'title': wn.synset('strictness.n.01'),
        'FEs': {
            'Agent': wn.synset('agentive_role.n.01'),
            'Controlled_entity': wn.synset('entity.n.01'),
            'Controlling_act': wn.synset('act.n.02'),
            'Issue': wn.synset('issue.n.01'),
            'Medium': wn.synset('medium.n.01'),
            'Degree': wn.synset('degree.n.01'),
            'Area': wn.synset('area.n.01'),
            'Judge': wn.synset('judge.n.01'),
            'Expressor': None,
            'Manner': wn.synset('manner.n.01'),
        },
        'LUs': {
            'authoritarian.a': wn.synset('authoritarian.a.01'),
            'indulgent.a': wn.synset('indulgent.a.01'),
            'lenient.a': wn.synset('indulgent.a.02'),
            'liberal.a': wn.synset('liberal.a.03'),
            'strict.a': wn.synset('nonindulgent.a.01'),
            'tolerant.a': wn.synset('tolerant.a.01'),
            'severe.a': wn.synset('austere.a.01'),
        }
    },
    'Sex': {
        'title': wn.synset('sexual_activity.n.01'),
        'FEs': {
            'Participant_1': wn.synset('participant.n.01'),
            'Participant_2': wn.synset('participant.n.01'),
            'Participants': wn.synset('participant.n.01'),
            'Domain': wn.synset('sphere.n.01'),
            'Duration': wn.synset('duration.n.03'),
            'Manner': wn.synset('manner.n.01'),
            'Means': wn.synset('means.n.03'),
            'Place': wn.synset('topographic_point.n.01'),
            'Purpose': wn.synset('purpose.n.01'),
            'Time': wn.synset('time.n.03'),
        },
        'LUs': {
            'bang.v': wn.synset('bang.v.05'),
            'bed.v': wn.synset('bed.v.04'),
            'bone.v': wn.synset('bone.v.02'),
            'bump uglies.v': wn.synset('bump.v.03'),
            'copulate.v': wn.synset('copulate.v.01'),
            'do it.v': wn.synset('do_it.v.01'),
            'do.v': wn.synset('perform.v.01'),
            'fuck.v': wn.synset('sleep_together.v.01'),
            'give.v': wn.synset('give.v.43'),
            'go at it.v': wn.synset('have_sex.v.01'),
            'have.v': wn.synset('take.v.35'),
            'intercourse.n': wn.synset('sexual_intercourse.n.01'),
            "jump (someone's) bones.idio": wn.synset('bones.n.01'),
            'jump.v': wn.synset('jump.v.03'),
            'knock boots.v': wn.synset('have_sex.v.01'),
            'lay.v': wn.synset('put.v.01'),
            'make love.v': wn.synset('sleep_together.v.01'),
            'make whoopee.a': wn.synset('whoopee.n.01'),
            'mate.v': wn.synset('copulate.v.01'),
            'pork.v': None,
            'quickie.n': wn.synset('quickie.n.01'),
            'sex.n': wn.synset('sexual_activity.n.01'),
            'shag.v': wn.synset('shag.n.4'),
            'slam.v': wn.synset('slam.v.01'),
            'take.v': wn.synset('take.v.35'),
        }
    },
    'Being_pregnant': {
        'title': wn.synset('pregnant.a.01'),
        'FEs': {
            'Father': wn.synset('father.n.01'),
            'Mother': wn.synset('mother.n.01'),
            'Parents': wn.synset('parent.n.01'),
            'Offspring': wn.synset('offspring.n.01'),
            'Duration': wn.synset('duration.n.03')
        },
        'LUs': {
            # NB: nltk.frament does not have this LUs
            # 'expecting.a': wn.synset('expectant.a.02'),
            # 'pregnant': wn.synset('pregnant.a.01'),
        }
    },
    'Dominate_situation': {
        'title': wn.synset('dominate.v.01'),
        'FEs': {
            'Agent': wn.synset('dominant.a.01'),
            'Situation': wn.synset('situation.n.01'),
            'Degree': wn.synset('degree.n.01'),
            'Duration': wn.synset('period_of_time.n.01'),
            'Manner': wn.synset('manner.n.01'),
            'Place': wn.synset('topographic_point.n.01'),
            'Time': wn.synset('time.n.03'),
        },
        'LUs': {
            'dominant.a': wn.synset('dominant.a.01'),
            'dominate.v': wn.synset('dominate.v.01'),
            'domination.n': wn.synset('domination.n.01'),
            'predominate.v': wn.synset('dominate.v.01'),
            'rule.v': wn.synset('rule.v.01')
        }
    },
    'Wearing': {
        'title': wn.synset('wear.v.01'),
        'FEs': {
            'Body_part': wn.synset('body_part.n.01'),
            'Clothing': wn.synset('clothing.n.01'),
            'Wearer': wn.synset('wearer.n.01'),
            'Degree': wn.synset('degree.n.01'),
            'Intended_wearing_location': wn.synset('place.n.01'),
            'Manner': wn.synset('manner.n.01'),
            'Purpose': wn.synset('purpose.n.01'),
            'Relative_location': wn.synset('location.n.01'),
            'Source': wn.synset('place.n.01'),
            'Time': wn.synset('time.n.02'),
        },
        'LUs': {
            'attired.a': wn.synset('attired.a.01'),
            'bare-armed.a': None,
            'bare-breasted.a': wn.synset('bare-breasted.a.01'),
            'bare-chested.a': None,
            'bare.a': wn.synset('bare.a.01'),
            'bare.v': wn.synset('bare.v.01'),
            'barefoot.a': wn.synset('barefoot.a.01'),
            'naked.a': wn.synset('naked.a.01'),
            'nude.a': wn.synset('nude.a.01'),
            'unclad.a': wn.synset('unclad.a.01'),
            'unshod.a': wn.synset('unshod.a.01'),
            'shoeless.a': wn.synset('shoeless.a.01'),
            'sockless.a': None,
            'nakedness.n': wn.synset('nakedness.n.01'),
            'nudity.n': wn.synset('nudity.n.01'),
            'clad.a': wn.synset('clad.a.01'),
            'clothed.a': wn.synset('clothed.a.01'),
            'wear.v': wn.synset('wear.v.01'),
            'dressed.a': wn.synset('appareled.a.01'),
            'bareheaded.a': wn.synset('bareheaded.a.01'),
            'barelegged.a': wn.synset('barelegged.a.01'),
            'hatless.a': wn.synset('hatless.a.01'),
            'coatless.a': None,
            'shirtless.a': None,
            'barefooted.a': wn.synset('barefoot.a.01'),
            'undressed.a': wn.synset('undressed.a.02'),
            'topless.a': wn.synset('topless.a.02'),
            'masked.a': wn.synset('costumed.a.0'),
            'hooded.a': None,
            'undress.n': wn.synset('undress.n.01'),
            'costumed.a': wn.synset('costumed.a.01'),
            'garbed.a': wn.synset('garbed.a.01'),
            'unclothed.a': wn.synset('unclothed.a.01'),
            'hatted.a': wn.synset('hatted.a.01'),
            'braless.a': wn.synset('braless.a.01'),
            'robed.a': wn.synset('robed.a.01'),
            'gloved.a': wn.synset('gloved.a.01'),
            'gloveless.a': wn.synset('gloveless.a.01'),
            'have on.v': wn.synset('wear.v.01'),
            'with on.idio': None,
            'have got on.v': wn.synset('wear.v.01'),
            'in.prep': wn.synset('wear.v.01'),
            'decked out.a': wn.synset('overdress.v.02'),
            'dolled up.a': wn.synset('dressed.s.04'),
            'got on.v': wn.synset('wear.v.01'),
            'sport.v': wn.synset('sport.v.01'),
            'swaddled.a': None,
            'swathed.a': wn.synset('swathe.v.01'),
        }
    }
}
